# Generated by Django 4.2.1 on 2023-06-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='identificador',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
